### ISSUE TITLE
Ignore vendor folders

### ISSUE THREAD

**Issue by carl-menezes-aql** [cuonglm/gocmt#3]
`gocmt -d . -i` also modifies vendored folders.

The default behaviour should be to ignore it, since you almost never want your vendored packages to be modified.

**Comment by cuonglm** [comment]
Hi @carl-menezes-aql Thanks for reporting.

I think it's better to always ignore `vendor/`, not just default behavior. It should be fixed in https://github.com/cuonglm/gocmt/commit/4df87c9631b229f03bbb27abd9c6193e437a45a4
