### ISSUE TITLE
is it necessary for every element in parens to add comment?

### ISSUE THREAD

**Issue by victor-simida** [cuonglm/gocmt#4]
In golint, it is ok if we have a comment above the parens
![image](https://user-images.githubusercontent.com/7692245/100582167-ca8c5b00-3323-11eb-9b46-217822047830.png)

**Comment by cuonglm** [comment]
Hi @victor-simida, would you mind elaborating more? What you described in the issue is exactly what's `gocmt` is doing, it only adds comment to the first element.

**Comment by victor-simida** [comment]
@cuonglm sorry 
What gocmt doing is :
![image](https://user-images.githubusercontent.com/7692245/100709461-210f9d00-33e9-11eb-91d1-846253688c7e.png)

I think we just need to add a comment above the paren like this :
![image](https://user-images.githubusercontent.com/7692245/100709521-3edd0200-33e9-11eb-9f33-f65c110c6ae3.png)

**Comment by victor-simida** [comment]
I change this feature in my forked repo like this 
![image](https://user-images.githubusercontent.com/7692245/100709625-68962900-33e9-11eb-9e85-698c5a70e0d9.png)

**Comment by cuonglm** [comment]
@victor-simida did you get latest version?

```
$ cat p.go
package p

const (
	A = "a"
	B = "b"
)
$ gocmt p.go
package p

// A ...
const (
	A = "a"
	B = "b"
)
```

**Comment by cuonglm** [comment]
@victor-simida Ops, sorry, you're right, actually I used outdated version.

**Comment by cuonglm** [comment]
FYI, the original PR is https://github.com/cuonglm/gocmt/pull/1

I think maybe it's ok to add a flag to toggle this behavior.

**Comment by victor-simida** [comment]
> FYI, the original PR is #1
> 
> I think maybe it's ok to add a flag to toggle this behavior.

The PR is [https://github.com/cuonglm/gocmt/pull/6](url)

If it is not elegant for you ,please let me know
